Virtual speaking room
Lapin-Learn/backend-main-server pull request #125
Opened 2024-12-24 05:47 UTC by ducviet5138

**New Endpoints**

**1. Generate Score Endpoint**
- URL: POST /ai/speaking/score
- Description: Generates a speaking score for a given question and order.
- Parameters:
`id (UUID)`: The ID of the speaking room.
`part (number)`: The part number of the question.
`order (number)`: The order of the question (1-based).
`file (Express.Multer.File)`: The uploaded audio file.
`user (ICurrentUser)`: The current user.

**2. Generate Question Endpoint**
- URL: GET /ai/speaking/questions
- Description: Generates a new question for the current user.
- Parameters:
`user (ICurrentUser)`: The current user.

**3. Generate Question by ID Endpoint**
- URL: GET /ai/speaking/questions/:id
- Description: Retrieves a question by its ID for the current user.
- Parameters:
`id (UUID)`: The ID of the question.
`user (ICurrentUser)`: The current user.

2024-12-25 15:28 UTC, NganTrucLe requested changes

2024-12-25 15:28 UTC, NganTrucLe commented on apps/main-api/src/modules/ai/speaking/ai-speaking.controller.ts
hmm ở FE thì chắc t k có muốn gọi thêm 1 endpoint evaluation để lấy kết quả chấm điểm nữa, tại có cái GET session detail trả result về rùi á :">
Với lại sr t chưa chạy local nên k rõ lắm có j sửa lời t nha, t muốn hỏi cái POST speech-evaluation é, là submit cái file, nhma thật ra cũng có PUT session là submit rùi á 😢 if else gọi tới module ai-speaking đc khum

2024-12-30 07:15 UTC, Quan0308 requested changes

2024-12-30 07:15 UTC, Quan0308 commented on apps/main-api/src/migrations/1735096141684-drop_columns_table_speaking_rooms.ts
bỏ file drop này đi

2024-12-30 07:42 UTC, Quan0308 requested changes

2024-12-30 07:42 UTC, Quan0308 commented on apps/main-api/src/migrations/1735014275871-add_table_speaking_rooms.ts
> +            isPrimary: true,
Thiếu isGenerated là true

2024-12-30 07:42 UTC, Quan0308 commented on libs/database/src/entities/speaking-rooms.entity.ts
Sao migration khác mà entity khác vậy

2024-12-30 14:02 UTC, Quan0308 requested changes

2024-12-30 14:02 UTC, Quan0308 commented on apps/main-api/src/migrations/1735014275871-add_table_speaking_rooms.ts
> +            name: "FK_SPEAKING_ROOMS_LEARNER_PROFILES",
Bỏ FK

2024-12-30 14:02 UTC, Quan0308 commented on apps/main-api/src/modules/ai/speaking/ai-speaking.service.ts
> +          results: [currentEvaluation],
Lưu estimatedScore là result của evaluation

2024-12-30 16:56 UTC, Quan0308 approved these changes
LGTM

2024-12-30 16:57 UTC, merged