Lap 81
Lapin-Learn/backend-main-server pull request #13
Opened 2024-08-13 03:54 UTC by MinEn1712

- View and update profile for everyone

2024-08-13 04:18 UTC, NganTrucLe requested changes

2024-08-13 04:18 UTC, NganTrucLe commented on apps/main-api/src/modules/user/user.controller.ts
> +  @Get("profile")
Gắn Swagger vô lunn ikk @MinEn1712

2024-08-13 04:18 UTC, NganTrucLe commented on apps/main-api/src/modules/user/user.controller.ts
> +  }
"everyone can view and update" á Mạnh, nên k cần decorator Roles đâu, lấy info từ @CurrentUser là đc òi

2024-08-13 04:41 UTC, Quan0308 requested changes

2024-08-13 04:41 UTC, Quan0308 commented on apps/main-api/src/modules/user/user.controller.ts
>    @Put(":id")
path nên là profile/:id

2024-08-13 04:41 UTC, Quan0308 commented on apps/main-api/src/modules/user/user.service.ts
> +      return { ...existedAccount, learnerProfile };
Chưa hiểu chỗ này lắm là tại sao mình phải join 2 object như thế này, nếu chỉ return `this.getUserById(id)` thì như thế nào, kh có id đó thì có trả error cho mình không. Nếu muốn trả exception thì có thể consider để vào trong hàm `getUserById`

2024-08-13 04:41 UTC, Quan0308 commented on apps/main-api/src/modules/user/user.controller.ts
>  @UseGuards(FirebaseJwtAuthGuard, RoleGuard)
Đưa RoleGuard vào các path cần check role vì controller này có những path kh cần check role

2024-08-13 04:41 UTC, Quan0308 commented on apps/main-api/src/modules/user/user.controller.ts
> +  @Roles(AccountRoleEnum.ADMIN, AccountRoleEnum.LEARNER)
Bỏ `decorator Roles` vì ai cũng có thể tự lấy profile của mình

2024-08-13 04:41 UTC, Quan0308 commented on apps/main-api/src/modules/user/user.controller.ts
> +  @Put("profile")
Bỏ `decorator Roles` vì ai cũng có thể tự update profile của mình

2024-08-13 04:52 UTC, MinEn1712 commented on apps/main-api/src/modules/user/user.service.ts
> +      return { ...existedAccount, learnerProfile };
hùm do t hỉu cái task là view profile é nên t include lun cái LearnerProfile, mí cái rank streak đồ :") hùm mà chắc bỏ cái nì xong dùng cái getUserById ở trên he do nì everyone view. Dị giờ cái nì chỉ view thông tin của Account thoi chứ chưa cần LearnerProfile hẻn

2024-08-13 06:22 UTC, Quan0308 commented on apps/main-api/src/modules/user/user.service.ts
> +      return { ...existedAccount, learnerProfile };
ý là trong cái `getUserById` của m đã lấy learner profile rồi á, chỗ relation true ấy, thì mình cũng đâu cần lấy cái object đó ra để join lại

2024-08-13 07:29 UTC, ducviet5138 commented on apps/main-api/src/modules/user/user.controller.ts
>  @Controller("users")
Được thì add swagger dô luôn nha

2024-08-14 16:00 UTC, Quan0308 approved these changes
LGTM

2024-08-14 16:03 UTC, merged