test(lap-75): auth controller and service
Lapin-Learn/backend-main-server pull request #14
Opened 2024-08-15 15:56 UTC by NganTrucLe

2024-08-19 13:07 UTC, Quan0308 requested changes

2024-08-20 00:52 UTC, vmathu commented on apps/main-api/src/modules/auth/__mocks__/auth.service.ts
thường folder structure bên t sẽ là file test vs file cần test chung 1 parent á chứ k tách folder, kiểu `main.ts` vs `main.spec.ts` sẽ k có tách folder test vs mock riêng, mock sẽ trong file test lun, còn nếu config nào dùng chung thì mới tạo file ngoài á, nhma đa số là mock trong file test hết để dễ check là test j á

2024-08-20 00:52 UTC, vmathu commented on apps/main-api/src/modules/auth/__mocks__/auth.service.ts
cái logger cx có thể mock lun á, nếu có những case mún test nó log đúng info k

2024-08-20 00:52 UTC, vmathu commented on apps/main-api/src/modules/auth/test/auth.service.spec.ts
> +import { AuthService } from "../auth.service";
ụa chỗ này là import cái service gốc chứ đâu phải cái mock đún hong, phải import cái mock để test chứ hả

2024-08-20 00:52 UTC, vmathu commented on apps/main-api/src/modules/auth/test/auth.service.spec.ts
> +import { RedisService } from "@app/shared-modules/redis";
thường các module sẽ phải mock hết á, t hong bik cái testing module của next sp cái đó ch, có r thì ok he

2024-08-20 00:52 UTC, vmathu commented on apps/main-api/src/modules/auth/test/auth.service.spec.ts
> +      // Act
act k có thì bỏ cmt ha

2024-08-20 00:52 UTC, vmathu commented on apps/main-api/src/modules/user/__mocks__/user.service.ts
> +export const AuthService = jest.fn().mockReturnValue({
tên service có nhầm hem nè

2024-08-20 00:52 UTC, vmathu commented on apps/main-api/src/modules/auth/test/auth.controller.spec.ts
> +      expect(authService.registerUser).toHaveBeenCalledWith(signInRequestMock.email, signInRequestMock.password);
cái này có thể tách thành test nhỏ trong service là `should call with correct parameters` ha chứ hem có test service trong controller á

2024-08-20 03:37 UTC, NganTrucLe commented on apps/main-api/src/modules/auth/__mocks__/auth.service.ts
folder __mocks__ t đọc là để mock service đó dùng chung, jest có thể tự nhận biết được khi dùng jest.mock(<đường dẫn>).
Còn t thấy nhiều file quá nên mới tách hẳn folder test gồm các file .spec ở trỏng á

2024-08-20 03:39 UTC, NganTrucLe commented on apps/main-api/src/modules/auth/test/auth.controller.spec.ts
> +      expect(authService.registerUser).toHaveBeenCalledWith(signInRequestMock.email, signInRequestMock.password);
hong hiểu lắm á :"> này copilot gen hoi à. Mình không cần phải test toHaveBeenCalledWith hay toHaveBeenCalled hẻ

2024-08-20 03:40 UTC, NganTrucLe commented on apps/main-api/src/modules/auth/test/auth.service.spec.ts
> +      // Act
Act vs assert chung á m, t truyền hàm act vô trong expect, somehow t k tách ra được tại nó sẽ throw lỗi, k pass test đó trước khi vô đc assert

2024-08-20 03:41 UTC, NganTrucLe commented on apps/main-api/src/modules/auth/test/auth.service.spec.ts
> +import { RedisService } from "@app/shared-modules/redis";
thì mock luôn rùi á bà, nó là để ref cái type vô, còn mock là 3 dòng jest.mock rồi á

2024-08-20 03:42 UTC, NganTrucLe commented on apps/main-api/src/modules/auth/test/auth.service.spec.ts
> +import { AuthService } from "../auth.service";
ụa tại mình test auth service thì t nghĩ phải import service gốc chứ, chỉ mock những dependency thui

2024-08-20 03:45 UTC, NganTrucLe commented on apps/main-api/src/modules/auth/test/stubs/account.stub.ts
:))) tại nó lỗi á, t comment lại trc, quên xóa. https://www.facebook.com/reel/1252961189001945 :))

2024-08-28 13:32 UTC, merged