feat(lap-95): get streak history
Lapin-Learn/backend-main-server pull request #20
Opened 2024-08-28 08:58 UTC by ducviet5138

- **Param**: ?start=2023-07-25 (Duolingo). Trong trường hợp không có param sẽ lấy streak trong 7 ngày, trường hợp có param -> Lấy streak từ **start** đến hiện tại.
- Response Duolingo:
![image](https://github.com/user-attachments/assets/7ea4095c-afa5-4472-bbdb-19a6c95bce22)
- Response hiện tại:
![image](https://github.com/user-attachments/assets/ffa2bc0c-e259-4412-b18e-06b01b1a097d)

2024-08-28 09:13 UTC, Quan0308 requested changes

2024-08-28 09:13 UTC, Quan0308 commented on apps/main-api/src/modules/streak/streak.service.ts
> +      const getDailyLoginActivities = await Account.getDailyLoginActivities(user.userId, startDate, yesterday);
Tạo static function bằng entity learner profile, đã có profile id trong current user

2024-08-28 13:55 UTC, NganTrucLe commented on apps/main-api/src/modules/streak/streak.controller.ts
> +  @UseGuards(RoleGuard)
Thiếu Swagger á :">>>, cho cái targetStreak lun

2024-10-06 08:44 UTC, Quan0308 requested changes

2024-10-06 08:44 UTC, Quan0308 commented on apps/main-api/src/modules/streak/streak.service.ts
>        const account = await Account.findOne({ where: { id: user.userId } });
Chạy lại api set target thử. Sao chỗ này không join với learner profile mà có property streak. Có thể đổi sang thẳng dùng query learner profile luon

2024-10-06 15:37 UTC, ducviet5138 commented on apps/main-api/src/modules/streak/streak.service.ts
>        const account = await Account.findOne({ where: { id: user.userId } });
Này cũ rồi nên query qua Account, mới fix qua LearnerProfile rồi

2024-10-07 06:48 UTC, Quan0308 approved these changes
LGTM

2024-10-07 06:48 UTC, merged