feat(lap-126): implement get question types of skill feature
Lapin-Learn/backend-main-server pull request #21
Opened 2024-09-03 06:43 UTC by Quan0308

2024-09-03 17:42 UTC, ducviet5138 requested changes

2024-09-03 17:42 UTC, ducviet5138 commented on libs/database/src/entities/question-type.entity.ts
> +  imageId: string;
Êi này t coi define trong cái của Trúc trong Slack thấy không giống á, có bản mới không gửi với

2024-09-03 17:42 UTC, ducviet5138 commented on libs/database/src/entities/question-type.entity.ts
> +  skill: SkillEnum;
này cho null à

2024-09-04 02:46 UTC, NganTrucLe approved these changes

2024-09-04 12:21 UTC, Quan0308 commented on libs/database/src/entities/question-type.entity.ts
> +  skill: SkillEnum;
Đang nghĩ rằng các question type không bị phụ thuộc và có thể không nằm trong skill nào, muốn đổi thì t đổi

2024-09-04 12:25 UTC, Quan0308 commented on libs/database/src/entities/question-type.entity.ts
> +  imageId: string;
Đã gửi trong Slack

2024-09-04 12:54 UTC, NganTrucLe approved these changes

2024-09-04 12:58 UTC, merged