feat(lap-174): impl lesson categories
Lapin-Learn/backend-main-server pull request #28
Opened 2024-09-17 15:59 UTC by ducviet5138

2024-09-17 17:29 UTC, Quan0308 requested changes

2024-09-17 17:29 UTC, Quan0308 commented on apps/main-api/src/modules/admin/admin.service.ts
> +        const orderMap = new Map<number, boolean>();
Chỗ này xử lý có vẻ hơi dài và lặp code ở order map, thử sử dụng `uniqBy` của lodash để tạo mảng phần tử không lặp về lessonId và order, từ đó chỉ sort, check exist và lưu.

2024-09-17 18:44 UTC, ducviet5138 commented on apps/main-api/src/modules/admin/admin.service.ts
> +        const orderMap = new Map<number, boolean>();
Giảm lại bớt khúc order với map r nha

2024-09-18 03:49 UTC, Quan0308 requested changes

2024-09-18 03:49 UTC, Quan0308 commented on apps/main-api/src/modules/admin/admin.service.ts
> +      return QuestionType.find();
group list question type theo skill

2024-09-18 03:49 UTC, Quan0308 commented on libs/types/src/dtos/admin/update-question-type.dto.ts
> +export class UpdateQuestionTypeDto extends PartialType(CreateQuestionTypeDto) {
Truyền thêm band score để re-order lesson theo band score

2024-09-18 11:52 UTC, Quan0308 approved these changes
LGTM

2024-09-18 11:52 UTC, merged