feat(lap-190): return bucket url in response data
Lapin-Learn/backend-main-server pull request #33
Opened 2024-09-22 09:27 UTC by ducviet5138

2024-09-22 12:51 UTC, Quan0308 commented on libs/database/src/subscribers/bucket.subscriber.ts
> +import { BucketService } from "apps/main-api/src/modules/bucket/bucket.service";
Sao không dùng path @apps v

2024-09-22 12:59 UTC, ducviet5138 commented on libs/database/src/subscribers/bucket.subscriber.ts
> +import { BucketService } from "apps/main-api/src/modules/bucket/bucket.service";
Chưa set á :))) Nó xài @app cho mấy thằng kia mà, apps nó là cái folder chứa mấy cái module ấy

2024-09-22 13:14 UTC, Quan0308 requested changes

2024-09-22 13:14 UTC, Quan0308 commented on libs/database/src/entities/question.entity.ts
Thêm left join image vào function `getQuestionTypeProgressOfLearner`

2024-09-23 01:27 UTC, Quan0308 approved these changes
LGTM

2024-09-23 01:27 UTC, merged