feat(lap-304): missions api
Lapin-Learn/backend-main-server pull request #48
Opened 2024-10-13 13:23 UTC by ducviet5138

2024-10-13 14:33 UTC, Quan0308 requested changes

2024-10-13 14:33 UTC, Quan0308 commented on apps/main-api/src/modules/mission/mission.helper.ts
> +  buildMissionsResponseData(data: ProfileMission[]) {
dùng interface

2024-10-13 14:33 UTC, Quan0308 commented on apps/main-api/src/modules/mission/mission.controller.ts
> +  @Get("daily")
Chưa hiểu vì sao tách thành 2 route khi query mission

2024-10-13 14:33 UTC, Quan0308 commented on libs/database/src/entities/profile-mission.entity.ts
> +        status: ProfileMissionStatusEnum.ASSIGNED,
Xem xét thử có nên hiện mission đã complete hay không

2024-10-13 14:38 UTC, ducviet5138 commented on apps/main-api/src/modules/mission/mission.controller.ts
> +  @Get("daily")
Thấy bên postman ai tạo 2 route rồi á nên t làm theo

2024-10-14 00:51 UTC, Quan0308 requested changes

2024-10-14 00:51 UTC, Quan0308 commented on libs/database/src/entities/profile-mission.entity.ts
> +    const beginOfDay = moment().tz("Asia/Saigon").startOf("day").toDate();
Xem thử mình có cần xử lý dài như vậy không, vì mỗi ngày chạy cron job để update profile mission

2024-10-14 02:40 UTC, Quan0308 requested changes

2024-10-14 02:40 UTC, Quan0308 commented on apps/main-api/src/modules/mission/mission.controller.ts
> +  @Get()
Thêm thông tin swagger

2024-10-14 03:10 UTC, Quan0308 approved these changes
LGTM

2024-10-14 03:11 UTC, merged