feat(lap-356): implement mission duration and distinct skills
Lapin-Learn/backend-main-server pull request #54
Opened 2024-10-19 16:38 UTC by Quan0308

- 2 availabe category for quest:
1. `TOTAL_DURATION_OF_LEARN_DAILY_LESSON`
2. `COMPLETE_LESSON_WITH_DIFFERENT_SKILLS`

- Test to check if complete required learning total duration and number of distinct skills

2024-10-20 10:09 UTC, NganTrucLe reviewed
v chắc còn cái mission nì thoi á 
![image](https://github.com/user-attachments/assets/eb9a2fdf-fd3f-4bc1-8f01-340193e3f1c1)
t thấy có cái mission complete_lesson with percentage 0% rùi, tức là có học là đc mà đây là daily á, nên nếu implement cho monthly, nó học 5 bài trong 1 ngày maybe cũng sẽ tính hoàn thành, trong khi mục tiêu là học trong 5 ngày.
t mới coi code thôi h t mới chuẩn bị chạy thử nhe

2024-10-22 12:55 UTC, Huy203 approved these changes

2024-10-23 13:04 UTC, NganTrucLe approved these changes

2024-10-23 13:07 UTC, NganTrucLe commented on apps/main-api/src/modules/mission/mission.helper.ts
> +              requirement: mission.quest.requirements,
t thấy build cũng fail chỗ nì á

2024-10-24 17:35 UTC, NganTrucLe requested changes

2024-10-24 17:35 UTC, NganTrucLe commented on libs/shared-modules/src/mission-factory/lesson-mission.service.ts
> +      const res = await LessonRecord.countDailyLessonRecordWithPercentageScore(this._learner.id, percentage);
hừm chỗ này nếu user đó học 1 bài > percentage rồi, thì hàm này sẽ return true. Tiếp theo học bài thứ 2 thì < percentage, nhưng vì đang count trong này, thì nó vẫn return true => hàm isMissionCompleted vẫn true

2024-10-24 17:35 UTC, NganTrucLe commented on apps/main-api/src/modules/lesson/lesson.service.ts
>        }
ở hàm này, chỗ `m.status === .....` m update thêm là nó có status .RECEIVED nữa nhe, tại vì bữa trước Việt có update á, để đánh dấu mission nào được nhận thưởng hay chưa.

2024-10-25 02:41 UTC, Quan0308 commented on apps/main-api/src/modules/lesson/lesson.service.ts
>        }
lúc đầu tính sửa nhưng t thấy merge của Việt thì để trong cái hám xử lý complete -> vậy thì sẽ sửa lại ngay ngoài này luôn

2024-10-26 02:48 UTC, NganTrucLe approved these changes

2024-10-26 02:53 UTC, merged