feat(lap-100): apply effect streak freeze
Lapin-Learn/backend-main-server pull request #65
Opened 2024-11-17 15:31 UTC by NganTrucLe

- Buy an item "Streak freeze"
- Use an item "Streak freeze" from your inventory
Precondition:
- Do not learn any lesson on yesterday

2024-11-18 17:41 UTC, Quan0308 requested changes

2024-11-18 17:41 UTC, Quan0308 commented on apps/main-api/src/modules/item/item-effect/streak-freeze-item.service.ts
> +      await this._learner.streak.increaseStreak();
Khi thực hiện freeze streak thì phải lưu action `daily streak` để đảm bảo tính thống nhất là 1 ngày tăng 1 streak

2024-11-18 17:41 UTC, Quan0308 commented on apps/main-api/src/modules/item/item-effect/streak-freeze-item.service.ts
> +  async applyEffect() {
Theo scenario thì nếu learner đang có `streak = 0` thì không apply -> chưa handle case đó. Tuy nhiên, trường hợp này sẽ khó nếu apply streak freeze là cho người dùng bấm sử dụng vật phẩm -> bàn lại case này

2024-11-18 17:41 UTC, Quan0308 commented on apps/main-api/src/modules/item/item-effect/streak-freeze-item.service.ts
> +      const freezeStreakAction = await Action.findOneOrFail({ where: { name: ActionNameEnum.FREEZE_STREAK } });
Nếu dùng `findOneOrFail` thì cần handle thêm error `EntityNotFound` để trả message dễ hiểu với client

2024-11-18 17:41 UTC, Quan0308 commented on apps/main-api/src/modules/item/item-effect/streak-freeze-item.service.ts
> +  private readonly _profileItem: ProfileItem;
Dùng interface thay vì class

2024-11-18 17:44 UTC, NganTrucLe commented on apps/main-api/src/modules/item/item-effect/streak-freeze-item.service.ts
> +      await this._learner.streak.increaseStreak();
bởi vì hôm nay dùng là dùng cho ngày hôm qua í, với lại bên FE cũng cần biết khi nào là dùng streak freeze trong endpoint history nên mới tạo thêm enum

2024-11-18 17:49 UTC, NganTrucLe commented on apps/main-api/src/modules/item/item-effect/streak-freeze-item.service.ts
> +      await this._learner.streak.increaseStreak();
còn daily_streak thì tính là các hành động học bài/luyện thi gì đi

2024-11-21 09:38 UTC, Quan0308 approved these changes
LGTM

2024-11-21 09:38 UTC, merged