feat(user): get all users, get user by id, update user, create user
Lapin-Learn/backend-main-server pull request #9
Opened 2024-08-08 12:09 UTC by MinEn1712

- Add CreateUserDto and UpdateUserByAdminDto
- Add UserRepository
- Add UserModule (controller, service, module)
- Features: Get all users, get user by id, update user, create user

2024-08-08 14:53 UTC, ducviet5138 commented on libs/database/src/base-repository/base.repository.ts
> +    const existedData = await this.repository.findOne(data);
cái này như nhớ bên VOU bị lỗi gì mà nó save thành 1 record khác chứ không phải update nè

2024-08-08 14:53 UTC, ducviet5138 commented on apps/main-api/src/modules/user/user.controller.ts
> +  @Get(":id")
này xài @Param cũng được nè

2024-08-08 14:53 UTC, ducviet5138 commented on apps/main-api/src/modules/user/user.controller.ts
> +  async getAllUsers(@Param() data: { offset: number; limit: number; role?: AccountRoleEnum }) {
cái này thấy DQ hay xài @Query nè

2024-08-08 14:53 UTC, ducviet5138 commented on apps/main-api/src/modules/user/user.controller.ts
> +@Controller("users")
này hình như phân hệ admin dùng phải không á? DQ có add mấy decorator check role rồi á, có thể thêm dô :))))

2024-08-09 14:06 UTC, Quan0308 requested changes

2024-08-09 14:06 UTC, Quan0308 commented on apps/main-api/src/modules/user/user.service.ts
> +      return this.userRepository.getAllUsers(offset, limit, role);
thay vì dùng repository, mình có thể dùng Account.findOne luôn. Nếu dùng lại nhiều lần, cân nhắc tạo static function trong class Account.
<img width="627" alt="Screenshot 2024-08-09 at 9 02 45 PM" src="https://github.com/user-attachments/assets/b5b3b0e6-c786-4e60-9b3f-4fce7965677a">

2024-08-09 14:06 UTC, Quan0308 commented on package.json
> +    "firebase": "^10.12.5",
Sao chỗ này có package firebase ta

2024-08-10 17:08 UTC, ducviet5138 requested changes

2024-08-10 17:08 UTC, ducviet5138 commented on apps/main-api/src/modules/user/user.controller.ts
> +@Controller("users")
nếu mà admin hết thì đem lên để cái @Roles bên ngoài luôn cũng được á

2024-08-11 11:37 UTC, Quan0308 approved these changes
LGTM

2024-08-11 11:38 UTC, merged